version: "3.9"

services:
    django:
        build:
            context: "./django/"
            args:
              PROJECT_NAME: "djangoweb"
        environment:
            - TZ=Asia/Taipei
        ports:
            - "${WEB_PORT}:8000"
        volumes:
            - django-src:/usr/src/app
        container_name: "django"
        restart: always

volumes:
    django-src:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "./src/"
        external: false
