version: "3.9"

services:
    django:
        build:
            context: "./django/"
            args:
              PY_VER: ${PY_VER}
              PROJECT_NAME: ${PROJECT_NAME}
              ALLOWED_HOSTS: ${ALLOWED_HOSTS}
        environment:
            - TZ=Asia/Taipei
        expose:
            - "${DJANGO_PORT}"
        volumes:
            - django-src:/usr/src/app
        container_name: "django"
        restart: always

    nginx:
        build:
            context: "./nginx/"
            args:
                NGINX_VERSION: ${NGINX_VERSION}
        environment:
            - TZ=Asia/Taipei
            - NGINX_PORT=${NGINX_PORT}
        depends_on:
            - django
        ports:
            - 8000:${NGINX_PORT}
        volumes:
            - nginx-config:/etc/nginx/templates/
            - ./src/${PROJECT_NAME}/static:/usr/share/nginx/html/static
            - ./src/${PROJECT_NAME}/media:/usr/share/nginx/html/media
        container_name: "${NGINX_NAME}"
        restart: always


volumes:
    django-src:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "./src/"
        external: false

    nginx-config:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "./config/nginx/"
        external: false
