ARG NGINX_VERSION
FROM nginx:${NGINX_VERSION}

# If you using proxy
# ENV http_proxy http://tmws1.pxy.sysco:8080
# ENV https_proxy http://tmws1.pxy.sysco:8080

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./default.conf.template /etc/nginx/templates/default.conf.template

RUN apk add bash
WORKDIR /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
