# Generated by Django 3.1.5 on 2021-01-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modal_DB', '0002_auto_20210124_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nickname',
            field=models.CharField(default='超值二手機', max_length=15, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modal_DB.pmodel', verbose_name='型號'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(default=2016, verbose_name='出廠年份'),
        ),
    ]
