# Generated by Django 3.1.5 on 2021-01-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modal_DB', '0003_auto_20210124_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nickname',
            field=models.CharField(default='超值二手機', max_length=30, verbose_name='摘要'),
        ),
    ]
