ARG PY_VER
FROM python:${PY_VER}

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
RUN mkdir /config
COPY requirements.txt /config/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /config/requirements.txt

ARG PROJECT_NAME
RUN django-admin startproject ${PROJECT_NAME}

WORKDIR /usr/src/app/${PROJECT_NAME}
ENV PROJECT_NAME=${PROJECT_NAME}
RUN python manage.py startapp mainsite
# CMD python manage.py runserver 0.0.0.0:8000
