# Generated by Django 3.1.5 on 2021-01-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTV01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
